Repository coforma/swift-tech-challenge, pull requests merged in 2024-03, with the labels that each got.

#3 Issue/initial repo setup
  .adr-dir
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/hcd-template.md
  .github/ISSUE_TEMPLATE/user-story-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  LICENSE
  README.md
  documentation/data/README.md
  documentation/data/raw_data/application_questions.csv
  documentation/data/raw_data/institutions.csv
  documentation/data/raw_data/institutions_data_dictionary.csv
  documentation/design/design.md
  documentation/engineering/adr/0001-record-architecture-decisions.md
  documentation/engineering/adr/0002-use-adr-tools-for-architectural-decisions.md
  documentation/engineering/adr/0003-use-signed-commits.md
  documentation/product/definition_of_done.md
  documentation/product/product.md
  documentation/research/research.md
Labels: Infrastructure

#7 Fixed bug with templates, revved some other documentaiton as well
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/user-story-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  documentation/design/design.md
  documentation/product/product.md
  documentation/research/research.md
Labels: ready for review

#10 Issue/Front end framework
  .eslintrc.yaml
  .gitignore
  .nvmrc
  .pre-commit-config.yaml
  README.md
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/page.tsx
  documentation/engineering/adr/0004-use-nextjs-for-frontend.md
  documentation/engineering/adr/0005-use-eslint.md
  documentation/engineering/adr/0006-use-uswds-styles.md
  next.config.mjs
  package.json
  tsconfig.json
  yarn.lock
Labels: ready for review

#21 Issue/Import and install SASS for front end styling
  app/layout.tsx
  next.config.mjs
  package.json
  styles/globals.scss
  styles/styles.scss
  styles/uswds-theme.scss
  yarn.lock
Labels: frontend, ready for review

#22 Terraform Bootstrap and Pipeline
  .github/workflows/pipeline.yml
  .github/workflows/terraform-deploy.yml
  .github/workflows/terraform-plan.yml
  .github/workflows/terraform-validate.yml
  .github/workflows/tf-deploy-all.yml
  .gitignore
  documentation/engineering/adr/0007-use-terraform-for-iac.md
  tf/projects/bootstrap/env/global.s3.tfbackend
  tf/projects/bootstrap/env/global.tfvars
  tf/projects/bootstrap/main.tf
  tf/projects/bootstrap/output.tf
  tf/projects/bootstrap/variables.tf
  tf/projects/test/env/prod.s3.tfbackend
  tf/projects/test/env/prod.tfvars
  tf/projects/test/env/stage.s3.tfbackend
  tf/projects/test/env/stage.tfvars
  tf/projects/test/main.tf
  tf/projects/test/variables.tf
Labels: Infrastructure, ready for review

#26 Issue/Create a Header Component
  app/components/PageHeader.tsx
  app/layout.tsx
  styles/globals.scss
  styles/page-header.scss
  styles/styles.scss
Labels: frontend, ready for review

#27 Update styling conventions and structure
  .eslintrc.yaml
  app/components/PageHeader.tsx
  app/components/index.tsx
  app/components/layout/PageHeader.module.scss
  app/components/layout/PageHeader.tsx
  app/layout.tsx
  app/styles/globals.scss
  app/styles/styles.scss
  app/styles/uswds-theme.scss
  styles/page-header.scss
  styles/styles.scss
Labels: frontend, ready for review

#30 Issue/Create a Footer Component
  app/components/index.tsx
  app/components/layout/PageFooter.module.scss
  app/components/layout/PageFooter.tsx
  app/components/layout/PageHeader.tsx
  app/layout.tsx
  app/styles/globals.scss
Labels: frontend, ready for review

#31 Issue/front end infra
  .github/workflows/app-build.yml
  .github/workflows/app-deploy.yml
  .github/workflows/app-lint.yml
  .github/workflows/pipeline.yml
  next.config.mjs
  tf/projects/bootstrap/deploy.tf
  tf/projects/bootstrap/env/global.tfvars
  tf/projects/bootstrap/main.tf
  tf/projects/bootstrap/output.tf
  tf/projects/bootstrap/variables.tf
Labels: Infrastructure, ready for review

#48 [#14] Add tooling for unit, integration, and accessibility tests
  .gitignore
  README.md
  app/components/layout/PageHeader.tsx
  cypress.config.ts
  documentation/engineering/adr/0008-use-jest-react-testing-library.md
  documentation/engineering/adr/0009-use-cypress.md
  documentation/engineering/adr/0010-use-axe-for-a11y-testing.md
  jest.config.ts
  package.json
  src/app/components/index.tsx
  src/app/components/layout/PageFooter.tsx
  src/app/components/layout/PageHeader.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles/PageFooter.scss
  src/app/styles/PageHeader.scss
  src/app/styles/globals.scss
  src/app/styles/styles.scss
  src/app/styles/uswds-theme.scss
  src/app/testing/cypress/e2e/app.cy.js
  src/app/testing/cypress/setupCypress.ts
  src/app/testing/cypress/utils/accessibility.js
  src/app/testing/jest/frontend/Homepage.test.tsx
  src/app/testing/jest/frontend/PageHeader.test.tsx
  src/app/testing/jest/setupJest.ts
  tsconfig.json
  yarn.lock
Labels: frontend, ready for review

#49 [#47] Add automated tests to CI pipeline
  .codeclimate.yml
  .github/workflows/pipeline.yml
  .github/workflows/testing.yml
  cypress.config.ts
  src/app/styles/styles.scss
  tsconfig.json
Labels: Infrastructure

#53 Issue/front end infra
  .github/workflows/app-build.yml
  .github/workflows/pipeline.yml
  tf/projects/bootstrap/env/global.tfvars
Labels: bug, Infrastructure, ready for review

#52 add dynamodb lib
  README.md
  jest.config.ts
  package.json
  src/app/testing/jest/frontend/utils/dynamodb-lib.test.ts
  src/app/utils/dynamodb-lib.ts
  yarn.lock
Labels: backend, ready for review

#29 Issue/data ingestion
  .github/ISSUE_TEMPLATE/hcd-template.md
  .github/ISSUE_TEMPLATE/user-story-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/terraform-deploy.yml
  .github/workflows/terraform-plan.yml
  .github/workflows/terraform-validate.yml
  .gitignore
  .nvmrc
  .pre-commit-config.yaml
  LICENSE
  documentation/design/design.md
  documentation/engineering/adr/0003-use-signed-commits.md
  documentation/engineering/adr/0004-use-nextjs-for-frontend.md
  documentation/engineering/adr/0008-nosql-approach-using-dynamo.md
  documentation/engineering/diagrams/etl-flow-data-ingestion.png
  documentation/engineering/diagrams/institutions-single-table-design.png
  documentation/product/definition_of_done.md
  documentation/product/product.md
  documentation/research/research.md
  src/app/styles/uswds-theme.scss
  tf/projects/bootstrap/env/global.s3.tfbackend
  tf/projects/bootstrap/env/global.tfvars
  tf/projects/bootstrap/main.tf
  tf/projects/bootstrap/output.tf
  tf/projects/bootstrap/variables.tf
  tf/projects/test/env/prod.s3.tfbackend
  tf/projects/test/env/prod.tfvars
  tf/projects/test/env/stage.s3.tfbackend
  tf/projects/test/env/stage.tfvars
  tf/projects/test/main.tf
  tf/projects/test/variables.tf
  utilities/data-ingestion/institutions.py
Labels: data

#55 Add scan function to dynamodb lib
  src/app/testing/jest/frontend/utils/dynamodb-lib.test.ts
  src/app/utils/dynamodb-lib.ts
Labels: backend, ready for review

#63 Issue/browse cards
  src/app/components/cards/CardIcon.tsx
  src/app/components/cards/CollegeCard.tsx
  src/app/components/index.tsx
  src/app/page.tsx
  src/app/styles/components/cards/CardIcon.scss
  src/app/styles/components/cards/CollegeCard.scss
  src/app/styles/components/layout/PageFooter.scss
  src/app/styles/components/layout/PageHeader.scss
  src/app/styles/styles.scss
  src/app/styles/uswds-theme.scss
  src/app/testing/jest/frontend/Homepage.test.tsx
  src/app/testing/jest/frontend/components/cards/CardIcon.test.tsx
  src/app/testing/jest/frontend/components/cards/CollegeCard.test.tsx
  src/app/testing/jest/frontend/components/layout/PageFooter.test.tsx
  src/app/testing/jest/frontend/components/layout/PageHeader.test.tsx
  src/app/types/college.tsx
  src/app/types/index.tsx
Labels: frontend, ready for review

#67 Issue/Create 404 page
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/styles/components/layout/PageFooter.scss
  src/app/styles/globals.scss
  src/app/styles/not-found.scss
  src/app/styles/styles.scss
  src/app/testing/jest/frontend/404.test.tsx
Labels: frontend, ready for review

#68 Bugfix/Bring back accessibility tests for CardIcon and CollegeCard
  src/app/testing/jest/frontend/components/cards/CardIcon.test.tsx
  src/app/testing/jest/frontend/components/cards/CollegeCard.test.tsx
Labels: frontend, ready for review

#73 Issue/front end infra
  .github/workflows/app-deploy.yml
  .github/workflows/app-int-test.yml
  .github/workflows/app-unit-test.yml
  .github/workflows/pipeline.yml
  .github/workflows/terraform-deploy.yml
  .pre-commit-config.yaml
  src/app/testing/cypress/e2e/app.cy.js
  tf/modules/frontend/api-gateway.tf
  tf/modules/frontend/cloudfront.tf
  tf/modules/frontend/deploy.tf
  tf/modules/frontend/lambda.tf
  tf/modules/frontend/main.tf
  tf/modules/frontend/outputs.tf
  tf/modules/frontend/variables.tf
  tf/projects/application/env/prod.s3.tfbackend
  tf/projects/application/env/prod.tfvars
  tf/projects/application/env/stage.s3.tfbackend
  tf/projects/application/env/stage.tfvars
  tf/projects/application/main.tf
  tf/projects/application/outputs.tf
  tf/projects/application/variables.tf
  tf/projects/bootstrap/output.tf
Labels: Infrastructure, ready for review

#72 Issue/Hero Image
  src/app/assets/hero-image-transparent.png
  src/app/assets/hero-image.png
  src/app/components/index.tsx
  src/app/components/layout/HeroImage.tsx
  src/app/page.tsx
  src/app/styles/browse.scss
  src/app/styles/components/layout/HeroImage.scss
  src/app/styles/components/layout/PageHeader.scss
  src/app/styles/styles.scss
  src/app/testing/jest/frontend/Homepage.test.tsx
  src/app/testing/jest/frontend/components/layout/HeroImage.test.tsx
Labels: frontend, ready for review

#83 Issue front end infra - fix conditions again
  .github/workflows/pipeline.yml
Labels: bug, Infrastructure, ready for review

#84 Issue (#79) Terraform backend
  tf/modules/frontend/lambda.tf
  tf/modules/frontend/variables.tf
Labels: Infrastructure, backend, ready for review

#90 Issue (#79) backend terraform
  tf/modules/frontend/lambda.tf
  tf/modules/frontend/variables.tf
  tf/projects/application/env/prod.tfvars
  tf/projects/application/env/stage.tfvars
  tf/projects/application/main.tf
  tf/projects/application/variables.tf
Labels: Infrastructure, backend, ready for review

#85 Add logic for loading images from s3 per institution
  package.json
  src/app/components/cards/CollegeCard.tsx
  src/app/public/picture_icon.png
  src/app/testing/jest/frontend/utils/institutions.test.ts
  src/app/testing/jest/frontend/utils/libs/s3-lib.test.ts
  src/app/types/college.tsx
  src/app/utils/institutions.ts
  src/app/utils/libs/s3-lib.ts
  yarn.lock
Labels: frontend, backend, ready for review

#92 Issue (#91) - Images not displaying
  tf/modules/frontend/cloudfront.tf
Labels: bug, Infrastructure, ready for review

#89 Bug fix/Tweak typography and spacing for browse page
  src/app/components/cards/CollegeCard.tsx
  src/app/components/layout/HeroImage.tsx
  src/app/styles/browse.scss
  src/app/styles/components/cards/CardIcon.scss
  src/app/styles/components/cards/CollegeCard.scss
  src/app/styles/components/layout/HeroImage.scss
  src/app/styles/components/layout/PageFooter.scss
  src/app/styles/components/layout/PageHeader.scss
  src/app/styles/globals.scss
Labels: frontend, ready for review

#86 Updated data ingestions
  .pre-commit-config.yaml
  documentation/engineering/adr/0008-nosql-approach-using-dynamo.md
  documentation/engineering/adr/0014-use-generative-ai-to-create-content-to-support-prototype.md
  documentation/engineering/diagrams/etl-ai-ingestion-flow.png
  utilities/data-ingestion/get-institution-description-from-bedrock.py
  utilities/data-ingestion/get-institution-image-from-bedrock.py
  utilities/data-ingestion/ingest-applications.py
  utilities/data-ingestion/ingest-institutions.py
  utilities/data-ingestion/institutions.py
Labels: data

#117 Bugfix/college card typing
  src/app/components/cards/CardIcon.tsx
  src/app/testing/jest/frontend/components/cards/CollegeCard.test.tsx
Labels: bug, frontend

#115 Ingest pngs and next image
  next.config.mjs
  src/app/components/cards/CollegeCard.tsx
  src/app/testing/jest/setupJest.ts
  src/app/types/college.tsx
  src/app/utils/institutions.ts
  utilities/data-ingestion/get-institution-description-from-bedrock.py
  utilities/data-ingestion/get-institution-image-from-bedrock.py
Labels: bug, enhancement, Infrastructure, data

#120 Issue (#95) - Application Performance
  tf/modules/frontend/cloudfront.tf
Labels: Infrastructure, ready for review

#99 Issue/browse card formatting
  src/app/components/cards/CollegeCard.tsx
  src/app/testing/jest/frontend/components/cards/CollegeCard.test.tsx
  src/app/testing/jest/frontend/utils/institutions.test.ts
  src/app/testing/jest/frontend/utils/masking.test.tsx
  src/app/testing/jest/setupJest.ts
  src/app/utils/institutions.ts
  src/app/utils/masking.ts
Labels: enhancement, frontend

#125 Check if lambda is updating before deploying new version
  .github/workflows/app-deploy.yml
  tf/modules/frontend/lambda.tf
  tf/projects/bootstrap/main.tf
Labels: Infrastructure, ready for review

#126 Remove unused image
  src/app/public/picture_icon.png
Labels: ready for review

#131 Issue/95 perf improvement 1
  next.config.mjs
  package.json
  tf/modules/frontend/lambda.tf
  yarn.lock
Labels: Infrastructure, ready for review

#133 Add image caching to cloudfront
  next.config.mjs
  tf/modules/frontend/api-gateway.tf
  tf/modules/frontend/cloudfront.tf
Labels: Infrastructure, ready for review

#130 Issue/apply page
  package.json
  src/app/[id]/apply/page.tsx
  src/app/components/cards/CollegeCard.tsx
  src/app/components/form/ApplicationForm.tsx
  src/app/components/form/TextArea.tsx
  src/app/components/form/TextField.tsx
  src/app/components/index.tsx
  src/app/styles/apply.scss
  src/app/styles/components/form/TextArea.scss
  src/app/styles/styles.scss
  src/app/testing/jest/frontend/Apply.test.tsx
  src/app/testing/jest/frontend/components/cards/CollegeCard.test.tsx
  src/app/testing/jest/frontend/components/form/TextArea.test.tsx
  src/app/testing/jest/frontend/components/form/TextField.test.tsx
  src/app/types/form.tsx
  src/app/types/index.tsx
  src/app/utils/institutions.ts
  yarn.lock
Labels: frontend, ready for review

#122 Details page
  src/app/[id]/page.tsx
  src/app/components/cards/CollegeCard.tsx
  src/app/components/cards/DetailsCards.tsx
  src/app/components/index.tsx
  src/app/testing/jest/frontend/DetailsPage.test.tsx
  src/app/testing/jest/frontend/components/cards/CollegeCard.test.tsx
  src/app/testing/jest/setupJest.ts
Labels: frontend, ready for review

#112 Add dynamo put function and scaffold application utility
  src/app/components/form/ApplicationForm.tsx
  src/app/testing/jest/frontend/utils/applications.test.ts
  src/app/testing/jest/frontend/utils/libs/dynamodb-lib.test.ts
  src/app/utils/applications.ts
  src/app/utils/libs/dynamodb-lib.ts
Labels: backend

#136 Initial images for the writeup
  documentation/product/assets/Challenge Scenario Problem.png
  documentation/product/assets/Early Solutioning.png
  documentation/product/assets/Key Insights.png
Labels: documentation

#138 Issue/details page pt2
  src/app/[id]/page.tsx
  src/app/components/cards/BannerCard.tsx
  src/app/components/cards/DetailsCards.tsx
  src/app/components/index.tsx
  src/app/components/layout/PageHeader.tsx
  src/app/styles/components/cards/BannerCard.scss
  src/app/styles/components/cards/DetailsCard.scss
  src/app/styles/components/layout/PageHeader.scss
  src/app/styles/styles.scss
  src/app/testing/jest/frontend/components/cards/BannerCard.test.tsx
  src/app/testing/jest/frontend/components/cards/DetailsCard.test.tsx
  src/app/types/college.tsx
Labels: frontend, ready for review

#142 Fix college card navigation
  src/app/[id]/page.tsx
  src/app/components/cards/CollegeCard.tsx
  src/app/styles/components/cards/CollegeCard.scss
  src/app/testing/jest/frontend/components/cards/CollegeCard.test.tsx
  src/app/testing/jest/setupJest.ts
Labels: bug, ready for review

#147 Build out content of confirmation page
  src/app/[id]/apply/confirmation/page.tsx
  src/app/assets/mail.png
  src/app/testing/jest/frontend/ConfirmationPage.test.tsx
Labels: frontend, ready for review

#156 Add spinner elsewhere
  src/app/[id]/apply/confirmation/page.tsx
  src/app/[id]/page.tsx
  src/app/components/form/ApplicationForm.tsx
  src/app/components/index.tsx
  src/app/components/layout/Browse.tsx
Labels: frontend, ready for review

#154 Issue/153 applicants infrastructure
  tf/modules/frontend/lambda.tf
  tf/modules/frontend/variables.tf
  tf/projects/application/env/prod.tfvars
  tf/projects/application/env/stage.tfvars
  tf/projects/application/env/test.tfvars
  tf/projects/application/main.tf
  tf/projects/application/variables.tf
  tf/projects/data/env/prod.tfvars
  tf/projects/data/env/stage.tfvars
  tf/projects/data/env/test.tfvars
  tf/projects/data/main.tf
  tf/projects/data/variables.tf
Labels: Infrastructure, backend, ready for review

#157 Spinner styling update
  src/app/styles/components/utilities/Spinner.scss
Labels: enhancement, frontend

#160 Issue (#159) Performance Improvements - Increase resources
  tf/modules/frontend/lambda.tf
Labels: Infrastructure, ready for review

#161 Confirmation Page Styling
  src/app/[id]/apply/confirmation/page.tsx
  src/app/assets/mail.png
  src/app/assets/mail.svg
  src/app/styles/apply.scss
  src/app/styles/components/cards/BannerCard.scss
  src/app/styles/components/form/ApplicationForm.scss
  src/app/styles/components/layout/PageHeader.scss
  src/app/styles/globals.scss
Labels: frontend

#164 Issue/ingest image creation update
  src/app/testing/jest/frontend/utils/institutions.test.ts
  src/app/testing/jest/setupJest.ts
  src/app/utils/institutions.ts
  utilities/data-ingestion/get-institution-image-from-bedrock.py
  utilities/data-ingestion/ingest-institutions.py
Labels: bug, data

#170 Bugfix/form validation
  package.json
  src/app/[id]/apply/page.tsx
  src/app/components/form/AppForm.tsx
  src/app/components/form/CheckboxField.tsx
  src/app/components/form/DropdownField.tsx
  src/app/components/form/TextArea.tsx
  src/app/components/form/TextField.tsx
  src/app/components/form/USWDSForm.tsx
  src/app/components/index.tsx
  src/app/components/modals/FilterModal.tsx
  src/app/schemas/schemas.ts
  src/app/styles/globals.scss
  src/app/testing/jest/frontend/components/form/TextArea.test.tsx
  src/app/testing/jest/frontend/components/form/TextField.test.tsx
  src/app/utils/filtering.ts
  src/app/verbiage/errors.ts
  yarn.lock
Labels: frontend

#178 Added images to post-mvp writeup
  documentation/design/Post-MVP Ecosystem Design Thinking.md
Labels: documentation

#174 Create researchplan.md
  documentation/research/researchplan.md
Labels: documentation

#173 Adding secondary research template
  documentation/research/Secondary research template.xlsx
Labels: documentation

#183 Update Post-MVP Ecosystem Design Thinking.md
  documentation/design/Post-MVP Ecosystem Design Thinking.md
Labels: documentation

#180 Default image
  src/app/assets/default-institution-image.png
  src/app/components/cards/BannerCard.tsx
  src/app/components/cards/CollegeCard.tsx
  src/app/components/utilities/ImageWithFallback.tsx
  src/app/testing/jest/frontend/components/utilities/ImageWithFallback.test.tsx
  utilities/data-ingestion/get-institution-image-from-bedrock.py
Labels: bug, enhancement, frontend

#190 Added priority tag to LCP above the fold
  src/app/components/layout/HeroImage.tsx
Labels: enhancement, frontend

#194 Performance (#159) - Update lambda memory
  tf/modules/frontend/lambda.tf
Labels: Infrastructure, ready for review

#200 Boost test coverage
  src/app/testing/jest/frontend/components/form/DropdownField.test.tsx
  src/app/testing/jest/frontend/components/modals/FilterModal.test.tsx
  src/app/testing/jest/frontend/utils/filtering.test.ts
  src/app/testing/jest/frontend/utils/institutions.test.ts
Labels: ready for review

#201 Issue/193 prod deploy 2
  .github/workflows/terraform-deploy.yml
  .github/workflows/tf-deploy-all.yml
Labels: Infrastructure, ready for review

#202 Issue/404
  src/app/assets/not_found.svg
  src/app/not-found.tsx
  src/app/styles/not-found.scss
  src/app/testing/jest/frontend/404.test.tsx
Labels: enhancement, frontend

#203 Design/final tweaks
  src/app/[id]/apply/confirmation/page.tsx
  src/app/assets/logo.svg
  src/app/components/cards/BannerCard.tsx
  src/app/components/cards/DetailsCards.tsx
  src/app/components/form/AppForm.tsx
  src/app/components/form/TextArea.tsx
  src/app/components/layout/HeroImage.tsx
  src/app/components/layout/PageFooter.tsx
  src/app/styles/apply.scss
  src/app/styles/browse.scss
  src/app/styles/components/cards/BannerCard.scss
  src/app/styles/components/cards/CollegeCard.scss
  src/app/styles/components/cards/DetailsCard.scss
  src/app/styles/components/form/TextArea.scss
  src/app/styles/components/layout/HeroImage.scss
  src/app/styles/components/layout/PageFooter.scss
  src/app/testing/jest/frontend/Apply.test.tsx
Labels: ready for review

#207 Issue/documentation update
  CONTRIBUTING.md
  documentation/engineering/assets/partial-aws-dashboard.png
  documentation/engineering/assets/revert-pr.png
Labels: documentation

#209 Issue/update
  src/app/components/form/AppForm.tsx
  src/app/components/form/TextArea.tsx
  src/app/components/form/USWDSForm.tsx
  src/app/schemas/schemas.ts
  src/app/testing/jest/frontend/components/form/TextArea.test.tsx
Labels: frontend
